// __fixtures__/svelteConfigProcessorProject/src/App.svelte
<script context="module" lang="ts">
import { fromModule } from "./module-util";
export const version = fromModule;
</script>

<script lang="ts">
  export
    let title = "Hello";

  import { secret } from "./private";
  import { greet } from "./utils";
  import missing from "non-existent-svelte-pkg";

  const message = greet(secret + String(missing));
  void message;
</script>

<main>{title} {version}</main>

// __fixtures__/vueConfigProcessorProject/src/App.vue
<template>
  <main>{{ message }}</main>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { secret } from "./private";
import { greet } from "./utils";
import missing from "non-existent-vue-pkg";

const message = ref(greet(secret + String(missing)));
</script>

<style scoped>
main {
  font-weight: 600;
}
</style>
